name: Github Package Registry npm Proxy
description: setup npm to use GPR as proxy

branding:
  icon: package
  color: red

inputs:
  path:
    description: path to write .npmrc file
    default: ${{ github.workspace }}/.npmrc

  scope:
    description: the github owner / org name to proxy through
    default: ${{ github.repository_owner }}

  token:
    description: github token to use with npm
    default: ${{ github.token }}

  proxy:
    description: enable proxy mode
    default: 'false'

  export_user_config:
    description: export the path to .npmrc as NPM_CONFIG_USERCONFIG
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm config --userconfig "${{ inputs.path }}" set //npm.pkg.github.com/:_authToken "${{ inputs.token }}"

        if [ "${{ inputs.proxy }}" != "true" ]; then
          npm config --userconfig "${{ inputs.path }}" set @${{ inputs.scope }}:registry="https://npm.pkg.github.com"
        else
          npm config --userconfig "${{ inputs.path }}" set registry="https://npm.pkg.github.com/${{ inputs.scope }}"
        fi

        if [ "${{ inputs.export_user_config }}" != "false" ]; then
          echo "NPM_CONFIG_USERCONFIG=${{ inputs.path }}" >> $GITHUB_ENV
        fi

