# ------------------------------------------------------- #
# Note: this file originates in template-action-composite #
# ------------------------------------------------------- #

name: pull_request_target

on: pull_request_target

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions: read-all

jobs:
  metadata:
    uses: ahmadnassri/actions/.github/workflows/metadata.yml@master

  auto-merge:
    needs: template-sync
    secrets: inherit
    uses: ahmadnassri/actions/.github/workflows/auto-merge.yml@master

    permissions:
      contents: write
      pull-requests: write
