# ------------------------------------------------------- #
# Note: this file originates in template-action-composite #
# ------------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions: read-all

jobs:
  metadata:
    uses: ahmadnassri/actions/.github/workflows/metadata.yml@master

  lint-commits:
    uses: ahmadnassri/actions/.github/workflows/lint-commits.yml@master

  lint-content:
    uses: ahmadnassri/actions/.github/workflows/lint-documentation.yml@master

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  release:
    needs:
      - metadata
      - commit-lint
      - mega-linter

    # only runs on main branch for non template repos
    if: |
      needs.metadata.outputs.repository_is_template == 'false' &&
      needs.metadata.outputs.repository_default_branch == github.ref_name

    permissions:
      contents: write
      packages: write

    uses: ahmadnassri/actions/.github/workflows/lint-documentation.yml@master

  alias:
    needs: release

    if: ${{ needs.release.outputs.published == 'true' }}

    permissions:
      contents: write

    strategy:
      matrix:
        alias:
          - version: v${{ needs.release.outputs.release-version-major }}
          - version: v${{ needs.release.outputs.release-version-major }}.${{ needs.release.outputs.release-version-minor }}

    uses: ahmadnassri/actions/.github/workflows/alias-tag.yml@master
    with:
      name: ${{ matrix.alias.version }}
