# ------------------------------------------------------- #
# Note: this file originates in template-action-composite #
# ------------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-action-composite.yml@master
    secrets: inherit
    permissions: write-all
